### PR TITLE
Demo run9 maks

### PR DESCRIPTION
**Pull request by gondiaz**
Implement rectangular holes in masks in demopp Run9.

### CODE REVIEW

**Comment by gondiaz** [comment]
Close the PR to solve the typo (maks --> masks)

**Comment by gondiaz** [comment]
Close the PR to solve the typo (maks --> masks)

**Comment by jacg** [comment]
> Close the PR to solve the typo (maks --> masks)

Is the `Edit` button next to the PR title not working?

**Comment by gondiaz** [comment]
No, but the typo was also in the branch name

**Comment by jacg** [comment]
The branch name doesn't leave any permanent record, so it doesn't really matter ... but it might inconvenience (surprise, catch out) people who try to check it out, so maybe it was worth fixing.

**Pull request closed without merging**
