### PR TITLE
Vertex generator for EL tables

### PR DESCRIPTION
**Pull request by jmalbos**
This pull request adds new vertex generators for the EL gaps of three detector geometries (NEXT-100, NEW and FLEX), as part of a new scheme for the generation of EL lookup tables.

(Cf. #53, which was closed after the transition of `next-exp/nexus` to public and the detachment of our forks.)

### CODE REVIEW

**Comment by jmalbos** [comment]
> Would it be interesting to assure that Zmax > Zmin to prevent from wrong behaviour ??

Done.

> Parameters disk_x and disk_y don't need to be >0.

I don't have any check like that, do I?

> In NEW, if you set a disk_x, it is changed of sign.

I don't understand.

**Comment by jmunozv** [comment]
Parameters disk_x and disk_y don't need to be >0.
In NEW, if you set a disk_x, it is changed of sign.

These comments were addressed by me in the commits:
 https://github.com/next-exp/nexus/pull/67/commits/c0a6cd921accc926d4bd6455dc0e2c91fe6926e9
https://github.com/next-exp/nexus/pull/67/commits/523f38f2ee3eabb7c672602e484953c7e60443f5

**Review by jmunozv — APPROVED** [review]
I approve this PR implementing the new Vertex Generator needed for Light Table productions.

**Comment by jmalbos** [comment]
> Parameters disk_x and disk_y don't need to be >0.
> In NEW, if you set a disk_x, it is changed of sign.
> 
> These comments were addressed by me in the commits:
> [c0a6cd9](https://github.com/next-exp/nexus/commit/c0a6cd921accc926d4bd6455dc0e2c91fe6926e9)
> [523f38f](https://github.com/next-exp/nexus/commit/523f38f2ee3eabb7c672602e484953c7e60443f5)

Understood. Since the comment comes from the old PR, I wasn't able to see when it had been written with respect to the commits.

**Pull request merged**
