### PR TITLE
Adding fix to catch.hh to fix compilation error on M1 macbook

### PR DESCRIPTION
**Pull request by kvjmistry**
This PR edits the catch.hh file to enable compilation of nexus with mac M1. It may also be possible to update catch2 to a newer version to have the same effect.

### CODE REVIEW

**Comment by jmalbos** [comment]
Hi @kvjmistry,

> It may also be possible to update catch2 to a newer version to have the same effect.

Did you actually try this?

**Comment by paolafer** [comment]
I've tried using the `v2.13.8` version (the latest stable one, it seems), and it seems to work alright. Shall we use this one, then?

**Comment by kvjmistry** [comment]
I updated the file to v2.13.8 and compiled no problem too. The latest commit includes this new file.

**Comment by gondiaz** [comment]
Works to me in Intel Mac

**Comment by jmalbos** [comment]
OK, so just to be sure: we would just need this second commit, right? If that is the case, you could remove the first one from the pull request or squash both together. You should also amend the commit comment to comply with the following conventions: https://cbea.ms/git-commit/
It could be simply something like this: _"Update Catch2 header to v2.13.8"_

**Comment by kvjmistry** [comment]
OK so I have removed the first commit and have everything as one commit which just replaces the header file to the new version.  The single commit has been renamed to "Update catch2 header to v2.13.8" (apologies for the poor name before). 

Please let me know if this is not the case!

**Comment by paolafer** [comment]
That's great, Krishan, I'll approve and merge the PR as soon as the tests have passed. I'll add the link to the git conventions in the wiki, by the way!

**Comment by jmalbos** [comment]
Great, @kvjmistry, and congrats for your first approved nexus PR!

**Review by paolafer — APPROVED** [review]
Catch2 header file has been updated to fix error compiling on M1 chip. Approved!

**Pull request merged**
