### PR TITLE
Lab generator

### PR DESCRIPTION
**Pull request by paolafer**
This PR takes the branch of PR #69 by @andLaing and rebases it on the current `master` branch.

### CODE REVIEW

**Comment by pnovella** [comment]
This branch has been validated with a dedicated muon simulation. The proper angular distribution of the muons is kept. It enhances the efficiency of the simulation: the fraction of simulated muons inducing interactions in the active volume is increased by a factor ~100

**Comment by pnovella** [comment]
This branch has been validated with a dedicated muon simulation. The proper angular distribution of the muons is kept. It enhances the efficiency of the simulation: the fraction of simulated muons inducing interactions in the active volume is increased by a factor ~100

**Comment by paolafer** [comment]
Great, can you also formally approve it? Go to `Files changed` --> `Review changes` --> `Approve`?

**Review by pnovella — APPROVED** [review]
This branch has been validated with a dedicated muon simulation. The proper angular distribution of the muons is kept. It enhances the efficiency of the simulation: the fraction of simulated muons inducing interactions in the active volume is increased by a factor ~100

**Pull request merged**
